Installation
AjinkyaDahale/Osdag pull request #2
Opened 2024-11-22 11:22 UTC by Zehen-249

Please make a new branch named Installation in the upstream repository and merge this PR into it.

2024-11-22 14:59 UTC, AjinkyaDahale requested changes
Apart from the comments, the first (merge) commit should not exist. Could you try rebasing?

2024-11-22 14:59 UTC, AjinkyaDahale commented on .gitignore
> -*.sqlite
Let's not remove this without confirming why it's there. The solution might be to make these files by ourselves from the sql.

2024-11-22 14:59 UTC, AjinkyaDahale commented on .gitignore
> +# commented
A comment saying "commented" is redundant.

2024-11-22 14:59 UTC, AjinkyaDahale commented on .gitignore
> +# *.sqlite
Don't leave it commented. Just delete the line. These lines can be recovered from the git history later if needed.

2024-11-22 14:59 UTC, AjinkyaDahale commented on .gitignore
> +
For now, we will ignore this commit until we decide how to best maintain the database. However, if we choose to keep this, 1) the file is called `.gitignore`; and 2) the message can just say "track/do not ignore `.sqlite` files".

2024-11-22 14:59 UTC, AjinkyaDahale commented on src/osdag/Common.py
> +IMG_STRUT_1 = str(files("osdag.data.ResourceFiles.images").joinpath("bA.png"))
Can you confirm if the `str(...)` call is necessary? As far as I know this is supposed to allow "path-like objects".

2024-11-22 15:00 UTC, AjinkyaDahale commented
> Please make a new branch named Installation in the upstream repository and merge this PR into it.

Indeed it is probably time to change the branch name. Is there any reason to call it "installation" though?

2024-11-24 16:34 UTC, Zehen-249 commented on .gitignore
> -*.sqlite
if the sqlite file is absent the application do not run.

2024-11-24 16:34 UTC, Zehen-249 commented on .gitignore
> +# commented
got it

2024-11-24 16:34 UTC, Zehen-249 commented on .gitignore
> +# *.sqlite
done

2024-11-24 16:35 UTC, Zehen-249 commented on src/osdag/Common.py
> +IMG_STRUT_1 = str(files("osdag.data.ResourceFiles.images").joinpath("bA.png"))
it has to be in string format. otherwise it is causing error

2024-11-24 16:36 UTC, Zehen-249 commented
> > Please make a new branch named Installation in the upstream repository and merge this PR into it.
> 
> Indeed it is probably time to change the branch name. Is there any reason to call it "installation" though?

> these were the issue i got while installing the osdag so i named it this way

2024-11-24 18:32 UTC, AjinkyaDahale commented on .gitignore
> -*.sqlite
Yes it doesn't, but sgould we include it or build it during installation is the question.

2024-11-24 18:33 UTC, AjinkyaDahale commented on src/osdag/Common.py
> +IMG_STRUT_1 = str(files("osdag.data.ResourceFiles.images").joinpath("bA.png"))
OK so pyqt isn't that well integrated maybe.

2024-11-24 18:35 UTC, AjinkyaDahale commented on .gitignore
> +
@Zehen-249 I gave option to choose "track" or "do not ignore" 😂.

2024-11-25 16:45 UTC, closed without merging

2024-11-26 07:40 UTC, AjinkyaDahale commented
> > these were the issue i got while installing the osdag so i named it this way

Could you get the exact error received?